name: ci

on:
  push:
    branches:
      - staging
      - qa
    tags:
      - 'v*'  # Run on version tags like v1.0.0

permissions:
  contents: "read"
  packages: "write"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Git Metadata
        id: meta
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "DOCKER_TAG=$TAG_NAME" >> $GITHUB_ENV
            echo "PUSH_LATEST=true" >> $GITHUB_ENV
          else
            echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
            echo "PUSH_LATEST=false" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        if: env.PUSH_LATEST == 'true'
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: | 
              ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ env.DOCKER_TAG }}
              ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
              
      - name: Build and push
        uses: docker/build-push-action@v6
        if: env.PUSH_LATEST == 'false'
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: | 
              ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ env.GIT_BRANCH }}


              
